### PR TITLE
Removing placement mode

### PR DESCRIPTION
**Pull request by leenlab2**
# Description

- Moved inspection to button west
- removed placement mode action mapping and relevant code
- Merged in `bgm-stems-integration`'s puzzle refactor
- Fixed wall mountable objects placement
- Hid other branching item when first is placed
- Fixed detection bug with VHS player

### Type of change

- Bug fix (non-breaking change which fixes an issue) 
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How to Integrate

Changes already applied in Main

# How Has This Been Tested?

- Pickup for normal items should work as expected
- Picking up poster and placing in memory scene should remove other poster
- Placing objects near puzzle target should snap to target

# Checklists
## Integration Checklist
- [x] I have attached this PR to the relevant Trello card
- [ ] **I have not touched the main Room scene**
- [x] My changes generate no new errors
- [ ] Any dependencies have already gone live on the `main` branch or were merged in separately
- [x] Any modifications to prefabs have been applied to the original prefab file

## Review Checklist
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have kept my test scenes/assets in a folder called "To Be Deleted," and will remove them before merging
- [x] I have requested a review from at least one (1) team member (preferably someone working on a related task)

### CODE REVIEW

**Comment by leenlab2** [comment]
[Change control button mappings such that button west is for inspection, button east is for cancel/go back](https://trello.com/c/UQUsuwux/253-change-control-button-mappings-such-that-button-west-is-for-inspection-button-east-is-for-cancel-go-back)

**Comment by leenlab2** [comment]
[Change object placement to snap to locations with no guide](https://trello.com/c/SPpPzCUl/259-change-object-placement-to-snap-to-locations-with-no-guide)

**Comment by leenlab2** [comment]
[Posters get placed upside down in memory scene](https://trello.com/c/bxPmx6VW/261-posters-get-placed-upside-down-in-memory-scene)

**Review by valeriewirianto — APPROVED** [review]
🚢

**Pull request merged**
