### PR TITLE
Main menu

### PR DESCRIPTION
**Pull request by leenlab2**
# Description

Changed the main menu to look like this: 
image
Also along the way i fixed issue #180 i modified PauseMenu too to prevent that error there. Basically just changed Highlighted sprite to the normal one.

### CODE REVIEW

**Comment by valeriewirianto** [comment]
Should the background video be pausing/glitching out like this? Might just be my MacBook

https://github.com/leenlab2/reminiscence/assets/90932776/3cbc5933-fca1-49c2-b9f7-c3106765aaca

**Comment by valeriewirianto** [comment]
I haven't tested the game this week starting from the main menu. I tried starting from main menu now and when picking up items and inspecting them, they don't appear at the centre of the screen anymore.
Screen Shot 2024-04-17 at 2 40 14 PM
Screen Shot 2024-04-17 at 2 40 31 PM

**Comment by leenlab2** [comment]
> Should the background video be pausing/glitching out like this? Might just be my MacBook
> Screen.Recording.2024-04-17.at.2.34.29.PM.mov

OOF yeah that's not supposed to happen. It runs fine on my end but that could be a performance issue - maybe the file is too big?

**Comment by leenlab2** [comment]
> I haven't tested the game this week starting from the main menu. I tried starting from main menu now and when picking up items and inspecting them, they don't appear at the centre of the screen anymore. Screen Shot 2024-04-17 at 2 40 14 PM Screen Shot 2024-04-17 at 2 40 31 PM

Huh. Does this still happen after we merged in the held item branch?

**Comment by valeriewirianto** [comment]
> > I haven't tested the game this week starting from the main menu. I tried starting from main menu now and when picking up items and inspecting them, they don't appear at the centre of the screen anymore. Screen Shot 2024-04-17 at 2 40 14 PM Screen Shot 2024-04-17 at 2 40 31 PM
> 
> Huh. Does this still happen after we merged in the held item branch?

I tried this on the held item branch from main menu and got the same results :(

**Comment by valeriewirianto** [comment]
> > Should the background video be pausing/glitching out like this? Might just be my MacBook
> > Screen.Recording.2024-04-17.at.2.34.29.PM.mov
> 
> OOF yeah that's not supposed to happen. It runs fine on my end but that could be a performance issue - maybe the file is too big?

Probs just my MacBook, not the first time it's happened :(

**Comment by leenlab2** [comment]
> > > I haven't tested the game this week starting from the main menu. I tried starting from main menu now and when picking up items and inspecting them, they don't appear at the centre of the screen anymore. Screen Shot 2024-04-17 at 2 40 14 PM Screen Shot 2024-04-17 at 2 40 31 PM
> > 
> > 
> > Huh. Does this still happen after we merged in the held item branch?
> 
> I tried this on the held item branch from main menu and got the same results :(

I think this only happens in the editor when you load it under the Free aspect ratio. I tried other screen sizes and it was fine. Will merge for now and if this happens in the build too will make another PR

**Pull request merged**
