### PR TITLE
New control scheme

### PR DESCRIPTION
**Pull request by leenlab2**
# Description

Control scheme is now:
- WASD for move
- Mouse for camera
- Left click for pickup
- Left click (hold) for place
- Right click for confirm place
- E for inspect
- Mouse for inspection rotate
- T for open/close TV

Misc. other changes:
- Fixed interaction pipeline. This should get rid of the bug in Issue #42 
- Swapped placeholder cursor icons as suggested
- Fixed bug where cursor switched to interactable mode once you hold an object

### Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Bug fix (non-breaking change which fixes an issue) 

## How to Integrate

Not needed - only scripts modified

# How Has This Been Tested?

Controls above should work as expected. The right interaction should always be performed, no matter the order in which buttons are pressed. Any attempts to press buttons when invalid does not work.

# Checklists
## Integration Checklist
- [ ] I have attached this PR to the relevant Trello card
- [x] **I have not touched the main Room scene**
- [x] My changes generate no new errors
- [x] Any dependencies have already gone live on the `main` branch or were merged in separately
- [x] Any modifications to prefabs have been applied to the original prefab file

## Review Checklist
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have kept my test scenes/assets in a folder called "To Be Deleted," and will remove them before merging
- [x] I have requested a review from at least one (1) team member (preferably someone working on a related task)

### CODE REVIEW

**Comment by leenlab2** [comment]
[Change control scheme according to UX feedback](https://trello.com/c/y7u5ijAm/231-change-control-scheme-according-to-ux-feedback)

**Comment by leenlab2** [comment]
[Invert + and o crosshairs](https://trello.com/c/OqHK3yDK/232-invert-and-o-crosshairs)

**Comment by leenlab2** [comment]
[cursor detects hit when no hit](https://trello.com/c/l7rOa7wi/236-cursor-detects-hit-when-no-hit)

**Comment by leenlab2** [comment]
[Bug fix: Add check if player is holding item to enable/disable inspection mode](https://trello.com/c/hIhMlK9X/240-bug-fix-add-check-if-player-is-holding-item-to-enable-disable-inspection-mode)

**Review by Infinityworld13 — APPROVED** [review]

**Pull request merged**
