### PR TITLE
Room rearrangement

### PR DESCRIPTION
**Pull request by leenlab2**
# Description

Bunch of asset updates.
- All assets that had to be changed due to polygon count (see trello) got updated models
- the attic model was updated to the new one
- attic environment rearranged to account for issues with couch
- lighting modified for new attic model
- fixed any issues that happened with puzzle targets as a result of this too
*may* have fixed the issue with the lighting in tape 2 memory (the light would sometimes turn the memory scene all white).
Issues #219 #218 #217 #201 #191 #188 

# How Has This Been Tested?

I've only tested music + uniform branches.

# Checklists
## Integration Checklist
- [ ] **I have not touched the main Room scene**
- [ ] My changes generate no new errors
- [ ] Any dependencies have already gone live on the `main` branch or were merged in separately
- [ ] Any modifications to prefabs have been applied to the original prefab file
- [ ] My changes were integrated into the main scene

## Review Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have kept my test scenes/assets in a folder called "To Be Deleted," and will remove them before merging
- [ ] I have requested a review from at least one (1) team member (preferably someone working on a related task)

### CODE REVIEW

**Comment by valeriewirianto** [comment]
Wondering if the lighting of the tape was always this dark 🤔 Not sure if players will see it upon startup of game and know to insert tape into TV

Screen Shot 2024-04-15 at 12 55 36 PM

**Comment by valeriewirianto** [comment]
nit: maybe move box on floor a little away from shelf to avoid cutting in of shelf into box
Screen Shot 2024-04-15 at 12 58 29 PM

**Comment by valeriewirianto** [comment]
nit: floating box in attic corner, cutting into rolled up rug against wall. Also cannot reach inside for contents if it has any
Screen Shot 2024-04-15 at 12 59 41 PM

**Comment by valeriewirianto** [comment]
Hmm is there a collider along the updated attic walls? I was able to just walk outside through a wall lol

Screen Shot 2024-04-15 at 1 03 13 PM

**Comment by leenlab2** [comment]
> Wondering if the lighting of the tape was always this dark 🤔 Not sure if players will see it upon startup of game and know to insert tape into TV
> 
> Screen Shot 2024-04-15 at 12 55 36 PM

There were two lights there in the past and it was causing some issues, but I think i can add it back proper

**Comment by leenlab2** [comment]
> Hmm is there a collider along the updated attic walls? I was able to just walk outside through a wall lol
> 
> Screen Shot 2024-04-15 at 1 03 13 PM

Whoops! Must be when i updated the textures right before bed forgot to turn on colliders. will fix that rq

**Comment by valeriewirianto** [comment]
nit: floating shirt puzzle target

Screen Shot 2024-04-15 at 1 21 57 PM

**Comment by valeriewirianto** [comment]
Placed down spray can in puzzle target threw this error. Maybe just because of this extra Element 2 that is empty.

Screen Shot 2024-04-15 at 1 24 44 PM

**Comment by valeriewirianto** [comment]
Found corner case bug. To reproduce:
- Open TV
- Hit esc to open the pause menu
- Click resume
- Hit T key to leave TV mode
- The player is now unable to move. I am able to move again if I open TV and enter into TV mode.

**Comment by valeriewirianto** [comment]
Yeah...this one's the same tutorialization issue...I think users will continue to miss the opening of the level 2 box containing the new tape + t-shirts... Wondering if it's not too much work to add a highlight to the box to tell users to check it out once they start level 2...

**Comment by valeriewirianto** [comment]
I went through Level 1 music branch and got to Level 2 just fine. But when I placed down all the objects for Level 2 band branch (band shirt branch), it did not update the TV with the final tape ending...

**Comment by valeriewirianto** [comment]
blue t-shirt cuts into sofa when placed in puzzle target
Screen Shot 2024-04-16 at 1 26 59 PM

**Review by valeriewirianto — APPROVED** [review]
Just blue t-shirt in lvl2 cuts into sofa when placed in puzzle target

**Pull request merged**
